CREATE DATABASE BMW;
USE BMW;
SELECT * FROM BMW_SALES;

##1-What is the total revenue generated from 2015–2025?
SELECT SUM(revenue) AS total_revenue
FROM bmw_sales;

##2-WHAT IS TOTAL UNIT SOLD?
SELECT SUM(QUANTITY) AS TOTAL_QUANTITY
FROM bmw_sales;

##3-WHAT IS TOTAL PROFIT?
SELECT sum(PROFIT) AS TOTAL_PROFIT
FROM bmw_sales;

##4-TOTAL REVENUE BY YEAR?
SELECT YEAR,SUM(REVENUE)AS TOTAL_REVENUE
FROM bmw_sales
GROUP BY YEAR
ORDER BY YEAR;

##5-Top 3 Selling Models by Units?
SELECT MODEL,sum(UNIT_PRICE) AS UNIT_SOLD
FROM BMW_SALES
GROUP BY MODEL
ORDER BY UNIT_SOLD
LIMIT 3;

SELECT* FROM BMW_SALES;

##6-REGION WISE REVENUE RANKING?
SELECT REGION,SUM(REVENUE) AS TOTAL_REVENUE,
RANK() OVER (ORDER BY SUM(REVENUE) DESC) AS REVENUE_RANK
FROM BMW_SALES
GROUP BY REGION;

##7-PROFIT MARGIN BY MODEL
SELECT MODEL,
ROUND(SUM(PROFIT)/SUM(REVENUE)*100,2) AS PROFIT_MARGIAN
FROM BMW_SALES
GROUP BY MODEL;

##8-BEST PERFORMING REGION EACH YEAR?
SELECT year, region, total_revenue
FROM (
SELECT year, region,
SUM(revenue) AS total_revenue,
RANK() OVER (PARTITION BY year ORDER BY SUM(revenue) DESC) AS rnk
FROM bmw_sales
GROUP BY year, region
) t
WHERE rnk = 1;

SELECT* FROM BMW_SALES;

##9-Which BMW model generates the highest total profit in each region?
SELECT region, model, total_profit
FROM (
SELECT region,model,SUM(profit) AS total_profit,
RANK() OVER (PARTITION BY region ORDER BY SUM(profit) DESC) AS rnk
FROM bmw_sales
GROUP BY region, model
) T
WHERE rnk = 1;
